const SessionActionType = {
  POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST',
  POST_LOGIN: 'POST_LOGIN',
  POST_LOGOUT_REQUEST: 'POST_LOGOUT_REQUEST',
  POST_LOGOUT: 'POST_LOGOUT',
  POST_REGISTER_REQUEST: 'POST_REGISTER_REQUEST',
  POST_REGISTER: 'POST_REGISTER',
};

export default SessionActionType;
